<?xml version="1.0"?>

<robot name="my_robo" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535"/>
  <xacro:property name="mass1" value="3.0"/>
  <xacro:property name="mass2" value="3.0"/>
  <xacro:property name="mass3" value="3.0"/>
  <xacro:property name="mass4" value="3.0"/>
  <xacro:property name="mass5" value="3.0"/>

  <xacro:property name="width1" value="0.1"/>
  <xacro:property name="width2" value="0.1"/>
  <xacro:property name="width3" value="0.4"/>
  <xacro:property name="width4" value="0.4"/>
  <xacro:property name="width5" value="0.01"/>
  <xacro:property name="width6" value="0.025"/>

  <xacro:property name="size_cam" value="0.03"/>
  <xacro:property name="offset_cam" value="0.03"/>


  <xacro:property name="sizeX" value="0.05"/>
  <xacro:property name="sizeY" value="0.05"/>
  
  <xacro:property name="offsetX" value="0.01"/>
  <xacro:property name="offsetY" value="0.05"/>

  <xacro:include filename="$(find my_robo_d)/urdf/my_robo.gazebo"/> i
  <xacro:include filename="$(find my_robo_d)/urdf/materials.xacro" />

  <link name="world"/>
  <joint name="fixed" type="fixed">
    <origin xyz="0 0 1.7" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <link name="link1">
    <collision>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${sizeX*2} ${sizeY*2}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (width1*width1 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass1 / 12.0 * (sizeX * sizeX + width1 * width1)}" />
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <origin xyz="${width1+offsetX} 0 0" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="link2"/>
    <axis xyz ="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link2">
    <collision>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (width2*width2 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass2 / 12.0 * (sizeX * sizeX + width2 * width2)}" />
    </inertial>

  </link>

  <joint name="joint2" type="continuous">
    <origin xyz="${width2-offsetY} ${offsetY} 0" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="link3"/>
    <axis xyz ="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>



  <link name="link3">
    <collision>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width3/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width3} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass3}"/>
      <inertia
        ixx="${mass3 / 12.0 * (width3*width3 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass3 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass3 / 12.0 * (sizeX * sizeX + width3 * width3)}" />
    </inertial>

  </link>

  <joint name="joint3" type="continuous">
    <origin xyz="${width3-offsetY} ${-offsetY} 0" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="link4"/>
    <axis xyz ="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link4">
    <collision>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width4/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width4} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass4}"/>
      <inertia
        ixx="${mass4 / 12.0 * (width4*width4 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass4 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass4 / 12.0 * (sizeX * sizeX + width4 * width4)}" />
    </inertial>

  </link>

  <joint name="joint4" type="continuous">
    <origin xyz="${width4+offsetX} 0 0" rpy="0 0 0"/>
    <parent link="link4"/>
    <child link="link5"/>
    <axis xyz ="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link5">
    <collision>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width5/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width5} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width5*width5 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width5 * width5)}" />
    </inertial>

  </link>

  <joint name="joint5" type="fixed">
    <origin xyz="${width5+offsetX} 0 0" rpy="0 0 0"/>
    <parent link="link5"/>
    <child link="link6"/>
  </joint>

  <link name="link6">
    <collision>
      <origin xyz="${width6/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width6/2} ${sizeX/2} ${sizeY/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width6/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width6/2} ${sizeX/2} ${sizeY/2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width6/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

  <joint name="cam_joint1" type="fixed">
    <origin xyz ="${width5+size_cam/2} ${offset_cam} 0"/>
    <parent link="link5"/>
    <child link="link_cam1"/>
  </joint>

  <link name="link_cam1">
    <collision>
      <origin xyz="0 ${offset_cam} 0"/>
      <geometry>
        <box size ="${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
    </collision>
		<visual>
      <origin xyz="0 ${offset_cam} 0" rpy="0 0 0"/>
      <geometry>
        <box size = "${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
      <material name="black"/>
    </visual>
		<inertial>
      <mass value = "0.001"/>
      <origin xyz = "0 ${offset_cam} 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy = "0" ixz = "0" 
								iyy= "0.0001" iyz="0" 
								izz="0.0001"/>
    </inertial>
	</link>

  <joint name="cam_joint2" type="fixed">
    <origin xyz ="${width5+size_cam/2} ${-offset_cam} 0"/>
    <parent link="link5"/>
    <child link="link_cam2"/>
  </joint>

  <link name="link_cam2">
    <collision>
      <origin xyz="0 ${-offset_cam} 0"/>
      <geometry>
        <box size ="${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
    </collision>
		<visual>
      <origin xyz="0 ${-offset_cam} 0" rpy="0 0 0"/>
      <geometry>
        <box size = "${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
      <material name="black"/>
    </visual>
		<inertial>
      <mass value = "0.001"/>
      <origin xyz = "0 ${-offset_cam} 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy = "0" ixz = "0" 
								iyy= "0.0001" iyz="0" 
								izz="0.0001"/>
    </inertial>
	</link>

<!--
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
-->

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>

   
