<?xml version="1.0"?>

<robot name="my_robo" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535"/>
  <xacro:property name="mass1" value="0.05"/>
  <xacro:property name="mass2" value="0.05"/>
  <xacro:property name="mass3" value="0.05"/>
  <xacro:property name="mass4" value="0.02"/>
  <xacro:property name="mass5" value="0.02"/>

  <xacro:property name="width1" value="0.1"/>
  <xacro:property name="width2" value="0.1"/>
  <xacro:property name="width3" value="0.2"/>
  <xacro:property name="width4" value="0.2"/>
  <xacro:property name="width5" value="0.01"/>
  <xacro:property name="width6" value="0.01"/>
  <xacro:property name="width7" value="0.01"/>

  <xacro:property name="ha" value="0.08"/>


  <xacro:property name="size_cam" value="0.01"/>
  <xacro:property name="offset_cam" value="0.03"/>

  <xacro:property name="low" value="-1.57"/>
  <xacro:property name="up" value="1.57"/>
  <xacro:property name="eff" value="10.0"/>
  <xacro:property name="vel" value="5.0"/>

  <xacro:property name="sizeX" value="0.05"/>
  <xacro:property name="sizeY" value="0.05"/>
  <xacro:property name="sizeXg" value="0.05"/>
  <xacro:property name="sizeYg" value="0.05"/>
  

  <xacro:property name="offsetX" value="0.01"/>
  <xacro:property name="offsetY" value="0.05"/>

  <xacro:include filename="$(find my_robo_d)/urdf/my_robo.gazebo"/> i
  <xacro:include filename="$(find my_robo_d)/urdf/materials.xacro" />

  <link name="world"/>
  <joint name="fixed" type="fixed">
    <origin xyz="0 0 0.4" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <link name="link1">
    <collision>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1/2} ${sizeX/2} ${sizeY/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${sizeX*2} ${sizeY*2}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width1/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (width1*width1 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass1 / 12.0 * (sizeX * sizeX + width1 * width1)}" />
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <origin xyz="${width1+offsetX} 0 0" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="link2"/>
    <axis xyz ="1 0 0"/>
    <dynamics damping="0.7"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
  </joint>

  <link name="link2">
    <collision>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width2/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (width2*width2 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass2 / 12.0 * (sizeX * sizeX + width2 * width2)}" />
    </inertial>

  </link>

  <joint name="joint2" type="revolute">
    <origin xyz="${width2-offsetY} ${offsetY} 0" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="link3"/>
    <axis xyz ="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
  </joint>



  <link name="link3">
    <collision>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width3/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width3} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width3/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass3}"/>
      <inertia
        ixx="${mass3 / 12.0 * (width3*width3 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass3 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass3 / 12.0 * (sizeX * sizeX + width3 * width3)}" />
    </inertial>

  </link>

  <joint name="joint3" type="revolute">
    <origin xyz="${width3-offsetY} ${-offsetY} 0" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="link4"/>
    <axis xyz ="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
  </joint>

  <link name="link4">
    <collision>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width4/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width4} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width4/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass4}"/>
      <inertia
        ixx="${mass4 / 12.0 * (width4*width4 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass4 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass4 / 12.0 * (sizeX * sizeX + width4 * width4)}" />
    </inertial>

  </link>

  <joint name="joint4" type="revolute">
    <origin xyz="${width4+offsetX} 0 0" rpy="0 0 0"/>
    <parent link="link4"/>
    <child link="link5"/>
    <axis xyz ="1 0 0"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link5">
    <collision>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width5/2} ${sizeX} ${sizeY}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width5} ${sizeX} ${sizeY}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width5/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width5*width5 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width5 * width5)}" />
    </inertial>

  </link>


<!--up_grip-->
  <joint name="joint5" type="revolute">
    <origin xyz="${width5} 0 0" rpy="0 0 0"/>
    <parent link="link5"/>
    <child link="link6"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
    <dynamics damping="0.7"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="link6">
    <collision>
      <origin xyz="${width6} 0 0.03" rpy="0 0 0"/>
      <geometry>
        <box size="${width6} ${sizeXg/2} ${sizeYg/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width6} 0 0.03" rpy="0 0 0"/>
      <geometry>
        <box size="${width6} ${sizeXg} ${sizeYg}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width6/2} 0 0.03" rpy="0 0 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

<!-- up grip2-->
  <joint name="joint7" type="fixed">
    <origin xyz="${width5} 0 0" rpy="0 0 0"/>
    <parent link="link6"/>
    <child link="link8"/>
  </joint>

  <link name="link8">
    <collision>
      <origin xyz="0.035 0 0.075" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.06 ${sizeXg} 0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 0 0.075" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.06 ${sizeXg} 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width6/2} 0 0.075" rpy="0 -0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

<!-- up grip3-->
  <joint name="joint9" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link8"/>
    <child link="link10"/>
  </joint>


  <link name="link10">
    <collision>
      <origin xyz="0.035 0.03 0.065" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 0.03 0.065" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0.03 0.03 0.065" rpy="0 0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

<!-- up grip4-->
  <joint name="joint10" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link8"/>
    <child link="link11"/>
  </joint>


  <link name="link11">
    <collision>
      <origin xyz="0.035 -0.03 0.065" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 -0.03 0.065" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0.03 -0.03 0.065" rpy="0 0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

<!--down grip-->
  <joint name="joint6" type="revolute">
    <origin xyz="${width5} 0 0" rpy="0 0 0"/>
    <parent link="link5"/>
    <child link="link7"/>
    <limit lower = "${low}" upper = "${up}" effort="${eff}" velocity="${vel}"/>
    <dynamics damping="0.7"/>
    <axis xyz="0 -1 0"/>
  </joint>

  <link name="link7">
    <collision>
      <origin xyz="${width6} 0 -0.03" rpy="0 0 0"/>
      <geometry>
        <box size="${width6} ${sizeXg/2} ${sizeYg/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${width6} 0 -0.03" rpy="0 0 0"/>
      <geometry>
        <box size="${width6} ${sizeXg} ${sizeYg}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width6/2} 0 -0.03" rpy="0 0 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>

<!--down grip2-->
  <joint name="joint8" type="fixed">
    <origin xyz="${width5} 0 0" rpy="0 0 0"/>
    <parent link="link7"/>
    <child link="link9"/>
  </joint>

  <link name="link9">
    <collision>
      <origin xyz="0.035 0 -0.075" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.06 ${sizeXg} 0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 0 -0.075" rpy="0 0.75 0"/>
      <geometry>
        <box size="0.06 ${sizeXg} 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${width6/2} 0 -0.075" rpy="0 0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>


<!-- down grip3-->
  <joint name="joint11" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link9"/>
    <child link="link12"/>
  </joint>


  <link name="link12">
    <collision>
      <origin xyz="0.035 0.03 -0.065" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 0.03 -0.065" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0.03 0.03 -0.065" rpy="0 -0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>


<!-- down grip4-->
  <joint name="joint12" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link9"/>
    <child link="link13"/>
  </joint>


  <link name="link13">
    <collision>
      <origin xyz="0.03 -0.03 -0.065" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.03 -0.03 -0.065" rpy="0 -0.75 0"/>
      <geometry>
        <box size="0.01 0.01 ${ha}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0.03 -0.03 -0.065" rpy="0 -0.75 0"/>
      <mass value="${mass5}"/>
      <inertia
        ixx="${mass5 / 12.0 * (width6*width6 + sizeY*sizeY)}" ixy="0.0" ixz="0.0"
        iyy="${mass5 / 12.0 * (sizeY*sizeY + sizeX * sizeX)}" iyz="0.0"
        izz="${mass5 / 12.0 * (sizeX * sizeX + width6 * width6)}" />
    </inertial>

  </link>




  <joint name="cam_joint1" type="fixed">
    <origin xyz ="${width5+size_cam/2} ${offset_cam} 0"/>
    <parent link="link5"/>
    <child link="link_cam1"/>
  </joint>

  <link name="link_cam1">
    <collision>
      <origin xyz="0 ${offset_cam} 0"/>
      <geometry>
        <box size ="${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
    </collision>
		<visual>
      <origin xyz="0 ${offset_cam} 0" rpy="0 0 0"/>
      <geometry>
        <box size = "${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
      <material name="black"/>
    </visual>
		<inertial>
      <mass value = "0.001"/>
      <origin xyz = "0 ${offset_cam} 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy = "0" ixz = "0" 
								iyy= "0.0001" iyz="0" 
								izz="0.0001"/>
    </inertial>
	</link>

  <joint name="cam_joint2" type="fixed">
    <origin xyz ="${width5+size_cam/2} ${-offset_cam} 0"/>
    <parent link="link5"/>
    <child link="link_cam2"/>
  </joint>

  <link name="link_cam2">
    <collision>
      <origin xyz="0 ${-offset_cam} 0"/>
      <geometry>
        <box size ="${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
    </collision>
		<visual>
      <origin xyz="0 ${-offset_cam} 0" rpy="0 0 0"/>
      <geometry>
        <box size = "${size_cam} ${size_cam} ${size_cam}"/>
      </geometry>
      <material name="black"/>
    </visual>
		<inertial>
      <mass value = "0.001"/>
      <origin xyz = "0 ${-offset_cam} 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy = "0" ixz = "0" 
								iyy= "0.0001" iyz="0" 
								izz="0.0001"/>
    </inertial>
	</link>

<!--
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
-->

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint5">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint6">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>

   
