arm_posision_controller:
  type: position_controllers/JointPositionController
  joints: 
     - joint1
     - joint2
     - joint3
     - joint4
  gains:
      joint1: {p: 1,  d: 0.1, i: 0.01, i_clamp: 1}
      joint2: {p: 1,  d: 0.1, i: 0.01, i_clamp: 1}
      joint3: {p: 1,  d: 0.1, i: 0.01, i_clamp: 1}
      joint4: {p: 1,  d: 0.1, i: 0.01, i_clamp: 1}
