arm_position_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
     - joint1
     - joint2
     - joint3
     - joint4
  gains:
      joint1: {p: 5,  d: 0.1, i: 0.001, i_clamp: 1}
      joint2: {p: 5,  d: 0.1, i: 0.001, i_clamp: 1}
      joint3: {p: 5,  d: 0.1, i: 0.001, i_clamp: 1}
      joint4: {p: 4,  d: 0.1, i: 0.001, i_clamp: 1}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 1.0, goal: 1.0}
      joint_2: {trajectory: 1.0, goal: 1.0}
      joint_3: {trajectory: 1.0, goal: 1.0}
      joint_4: {trajectory: 1.0, goal: 1.0}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
